server:
    port: 8081


spring:
    application:
        name: "demo"
    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}

aws:
    region: ${AWS_REGION:us-east-1}
    endpoint-url: ${DYNAMODB_ENDPOINT:http://localhost:8000}
    dynamodb:
        chat-table: "Chat"
        message-table: "Message"
        members-table: "Members"
        user-table: "User"
        missing-message-table: "MissingMessage"